from . import document_tag
from . import document_folder
from . import document
from . import document_upload_wizard
from . import folder_wizard
from . import preview_wizard
from . import actions_wizard     
from . import rename_wizard          
from . import properties_wizard  